import { Product, Customer, Order, ShakeIntakeLog, SeminarAttendance, Invoice, User } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Coach Ananya Roy',
    email: 'ananya@afnutrition.com',
    role: 'admin',
    branch: 'Ayanavaram Main Branch',
  },
  {
    id: 'USR-002',
    name: 'Coach Rajesh Kumar',
    email: 'rajesh@afnutrition.com',
    role: 'coach',
    branch: 'Ayanavaram Main Branch',
  },
  {
    id: 'USR-003',
    name: 'Pooja Sharma',
    email: 'pooja@afnutrition.com',
    role: 'cashier',
    branch: 'Ayanavaram Main Branch',
  },
  {
    id: 'USR-004',
    name: 'Suresh Kitchen Lead',
    email: 'suresh@afnutrition.com',
    role: 'kitchen',
    branch: 'Ayanavaram Main Branch',
  }
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'PRD-001',
    code: 'SHK-MNG',
    name: 'Mango Delight Protein Shake',
    category: 'Shakes',
    description: 'Fresh tropical mango blended with premium isolate protein, skimmed milk & chia seeds.',
    price: 150,
    costPrice: 65,
    stock: 45,
    minStockAlert: 10,
    active: true,
    flavor: 'Mango',
    nutritionInfo: { calories: 220, protein: 24, carbs: 22, fat: 3 },
  },
  {
    id: 'PRD-002',
    code: 'SHK-KLF',
    name: 'Chocolate Kulfi Shake',
    category: 'Shakes',
    description: 'Rich dark chocolate infused with traditional Indian kulfi spices and high protein blend.',
    price: 160,
    costPrice: 70,
    stock: 38,
    minStockAlert: 10,
    active: true,
    flavor: 'Chocolate Kulfi',
    nutritionInfo: { calories: 240, protein: 26, carbs: 20, fat: 4 },
  },
  {
    id: 'PRD-003',
    code: 'SHK-VAN',
    name: 'Vanilla Protein Fusion',
    category: 'Shakes',
    description: 'Smooth French vanilla protein shake enriched with multivitamins and fiber.',
    price: 150,
    costPrice: 60,
    stock: 50,
    minStockAlert: 10,
    active: true,
    flavor: 'Vanilla',
    nutritionInfo: { calories: 210, protein: 25, carbs: 18, fat: 2.5 },
  },
  {
    id: 'PRD-004',
    code: 'SHK-STR',
    name: 'Strawberry Blast Shake',
    category: 'Shakes',
    description: 'Real farm strawberry crush combined with whey isolate and Greek yogurt base.',
    price: 155,
    costPrice: 68,
    stock: 28,
    minStockAlert: 8,
    active: true,
    flavor: 'Strawberry',
    nutritionInfo: { calories: 215, protein: 24, carbs: 21, fat: 2 },
  },
  {
    id: 'PRD-005',
    code: 'SHK-ROS',
    name: 'Royal Rose & Cardamom Shake',
    category: 'Shakes',
    description: 'Aromatic pure Damascus rose extracts with crushed cardamom and whey protein.',
    price: 165,
    costPrice: 72,
    stock: 22,
    minStockAlert: 8,
    active: true,
    flavor: 'Rose',
    nutritionInfo: { calories: 230, protein: 24, carbs: 22, fat: 3.5 },
  },
  {
    id: 'PRD-006',
    code: 'SHK-CNC',
    name: 'Cookies & Cream Ultra Shake',
    category: 'Shakes',
    description: 'Crunchy healthy protein cookie crumbles folded into thick creamy vanilla base.',
    price: 175,
    costPrice: 78,
    stock: 18,
    minStockAlert: 5,
    active: true,
    flavor: 'Cookies & Cream',
    nutritionInfo: { calories: 260, protein: 27, carbs: 25, fat: 4.5 },
  },
  // Combos
  {
    id: 'PRD-007',
    code: 'CMB-WLB',
    name: 'Weight Loss Blast Combo',
    category: 'Combos',
    description: '1x Mango Delight Shake + 1x Lemon Fresh Energy Tea + 1x Aloe Digest Shot.',
    price: 260,
    costPrice: 110,
    stock: 35,
    minStockAlert: 10,
    active: true,
    isCombo: true,
    comboItems: ['Mango Delight Shake', 'Lemon Fresh Energy Tea', 'Aloe Digest Shot'],
    nutritionInfo: { calories: 245, protein: 26, carbs: 24, fat: 3 },
  },
  {
    id: 'PRD-008',
    code: 'CMB-ENR',
    name: 'Energy & Immunity Power Combo',
    category: 'Combos',
    description: '1x Chocolate Kulfi Shake + 1x Peach Iced Energy Tea + Protein Booster.',
    price: 280,
    costPrice: 120,
    stock: 25,
    minStockAlert: 8,
    active: true,
    isCombo: true,
    comboItems: ['Chocolate Kulfi Shake', 'Peach Iced Energy Tea', 'Protein Booster Scoop'],
    nutritionInfo: { calories: 290, protein: 34, carbs: 22, fat: 4 },
  },
  {
    id: 'PRD-009',
    code: 'CMB-WLN',
    name: 'Daily Wellness Starter Duo',
    category: 'Combos',
    description: '1x Vanilla Protein Fusion + 1x Ginger Tulsi Detox Tea.',
    price: 230,
    costPrice: 95,
    stock: 30,
    minStockAlert: 10,
    active: true,
    isCombo: true,
    comboItems: ['Vanilla Protein Fusion', 'Ginger Tulsi Detox Tea'],
    nutritionInfo: { calories: 220, protein: 25, carbs: 19, fat: 2.5 },
  },
  // Energy Teas
  {
    id: 'PRD-010',
    code: 'TEA-LMN',
    name: 'Lemon Fresh Energy Tea',
    category: 'Energy Teas',
    description: 'Metabolism-boosting thermogenic herbal tea with zesty natural lemon.',
    price: 90,
    costPrice: 30,
    stock: 65,
    minStockAlert: 15,
    active: true,
    nutritionInfo: { calories: 15, protein: 1, carbs: 2, fat: 0 },
  },
  {
    id: 'PRD-011',
    code: 'TEA-PCH',
    name: 'Peach Iced Energy Tea',
    category: 'Energy Teas',
    description: 'Refreshing cold peach botanical tea rich in natural polyphenols & antioxidants.',
    price: 95,
    costPrice: 32,
    stock: 40,
    minStockAlert: 12,
    active: true,
    nutritionInfo: { calories: 18, protein: 1, carbs: 3, fat: 0 },
  },
  {
    id: 'PRD-012',
    code: 'TEA-GNG',
    name: 'Ginger Tulsi Detox Tea',
    category: 'Energy Teas',
    description: 'Ayurvedic Holy Basil (Tulsi) with real crushed ginger for digestion and gut health.',
    price: 90,
    costPrice: 28,
    stock: 55,
    minStockAlert: 15,
    active: true,
    nutritionInfo: { calories: 12, protein: 1, carbs: 2, fat: 0 },
  },
  // Add-ons
  {
    id: 'PRD-013',
    code: 'ADD-PRO',
    name: 'Protein Booster Scoop (+10g)',
    category: 'Add-ons',
    description: 'Extra 10g pure unflavored whey/soy protein isolate scoop.',
    price: 50,
    costPrice: 20,
    stock: 90,
    minStockAlert: 20,
    active: true,
    nutritionInfo: { calories: 40, protein: 10, carbs: 0, fat: 0 },
  },
  {
    id: 'PRD-014',
    code: 'ADD-CHI',
    name: 'Organic Chia & Flax Seed Mix',
    category: 'Add-ons',
    description: 'Rich in Omega-3 fatty acids, dietary fiber, and healthy fats.',
    price: 35,
    costPrice: 12,
    stock: 70,
    minStockAlert: 15,
    active: true,
    nutritionInfo: { calories: 45, protein: 2, carbs: 4, fat: 3 },
  },
  {
    id: 'PRD-015',
    code: 'ADD-ALO',
    name: 'Aloe Vera Concentrate Shot',
    category: 'Add-ons',
    description: 'Soothing digestive health booster supporting nutrient absorption.',
    price: 40,
    costPrice: 15,
    stock: 45,
    minStockAlert: 10,
    active: true,
    nutritionInfo: { calories: 10, protein: 0, carbs: 2, fat: 0 },
  },
  // Protein Snacks
  {
    id: 'PRD-016',
    code: 'SNK-BAR',
    name: 'AF Crunchy Protein Granola Bar',
    category: 'Protein Snacks',
    description: 'Baked oats, almonds, dark chocolate chips & whey protein bar (15g protein).',
    price: 110,
    costPrice: 48,
    stock: 4, // Intentionally low to trigger Low Stock Alert
    minStockAlert: 10,
    active: true,
    nutritionInfo: { calories: 190, protein: 15, carbs: 18, fat: 6 },
  },
  {
    id: 'PRD-017',
    code: 'SNK-BIT',
    name: 'Nutty Protein Energy Bites (4pcs)',
    category: 'Protein Snacks',
    description: 'Dates, walnuts, peanut butter and raw cocoa energy balls.',
    price: 120,
    costPrice: 50,
    stock: 3, // Intentionally low to trigger alert
    minStockAlert: 8,
    active: true,
    nutritionInfo: { calories: 210, protein: 12, carbs: 24, fat: 8 },
  }
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'AF-2026-0001',
    fullName: 'Karthik Ramanathan',
    phone: '9841234567',
    email: 'karthik.r@gmail.com',
    gender: 'Male',
    age: 34,
    address: '12/4 Gandhi Road, Ayanavaram, Chennai',
    branch: 'Ayanavaram Main Branch',
    inviterType: 'Friend/Family',
    inviterName: 'Suresh Menon',
    inviterContact: '9840011223',
    counselingBy: 'Coach Ananya Roy',
    healthGoals: ['Weight Loss', 'Fat Loss', 'Energy Boost'],
    medicalNotes: 'Mild lactose sensitivity - prefers water/skimmed milk base',
    customerType: 'New Customer',
    currentProgram: 'Weight Loss & Energy Program',
    programDuration: '30 Days',
    durationInDays: 30,
    startDate: '2026-08-15',
    endDate: '2026-09-14',
    allottedShakes: 30,
    consumedShakes: 21,
    remainingShakes: 9,
    dailyShakeFrequency: 1,
    pricePerDay: 150,
    totalPlanCost: 4500,
    amountPaid: 4500,
    balanceDue: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    status: 'Active',
    clubVisitsCount: 21,
    seminarAttendanceCount: 2,
    totalOrdersCount: 6,
    totalSpent: 5350,
    createdAt: '2026-08-15T09:30:00Z',
    updatedAt: '2026-09-04T10:15:00Z',
  },
  {
    id: 'AF-2026-0002',
    fullName: 'Priya Sundaram',
    phone: '9884567890',
    email: 'priya.sundaram@yahoo.com',
    gender: 'Female',
    age: 29,
    address: '45 Lake View Street, Kilpauk, Chennai',
    branch: 'Ayanavaram Main Branch',
    inviterType: 'Digital/Social Media',
    inviterName: 'Instagram Campaign',
    counselingBy: 'Coach Rajesh Kumar',
    healthGoals: ['Muscle Tone', 'Daily Wellness', 'Gut Health'],
    medicalNotes: 'None',
    customerType: 'Existing Customer',
    currentProgram: 'Metabolic Reset & Wellness Plan',
    programDuration: '60 Days',
    durationInDays: 60,
    startDate: '2026-07-20',
    endDate: '2026-09-18',
    allottedShakes: 60,
    consumedShakes: 46,
    remainingShakes: 14,
    dailyShakeFrequency: 1,
    pricePerDay: 150,
    totalPlanCost: 9000,
    amountPaid: 9000,
    balanceDue: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'Card',
    status: 'Active',
    clubVisitsCount: 46,
    seminarAttendanceCount: 3,
    totalOrdersCount: 12,
    totalSpent: 10840,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-09-04T08:45:00Z',
  },
  {
    id: 'AF-2026-0003',
    fullName: 'Vikram Venkatesh',
    phone: '9790123456',
    email: 'vikram.v@outlook.com',
    gender: 'Male',
    age: 42,
    address: '77 Medavakkam Tank Rd, Kellys, Chennai',
    branch: 'Ayanavaram Main Branch',
    inviterType: 'Member',
    inviterName: 'Karthik Ramanathan',
    inviterContact: '9841234567',
    counselingBy: 'Coach Ananya Roy',
    healthGoals: ['Fat Loss', 'Stamina'],
    medicalNotes: 'Hypertension controlled by diet',
    customerType: 'Associate',
    associateId: 'ASC-003',
    convertedToAssociateAt: '2026-08-25',
    currentProgram: 'Associate Partner & Wellness Ambassador Plan',
    programDuration: '21 Days',
    durationInDays: 21,
    startDate: '2026-08-25',
    endDate: '2026-09-15',
    allottedShakes: 21,
    consumedShakes: 10,
    remainingShakes: 11,
    dailyShakeFrequency: 1,
    pricePerDay: 160,
    totalPlanCost: 3360,
    amountPaid: 3360,
    balanceDue: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    status: 'Active',
    clubVisitsCount: 10,
    seminarAttendanceCount: 1,
    totalOrdersCount: 3,
    totalSpent: 3820,
    remarks: 'Promoted from active client to Wellness Associate Partner',
    createdAt: '2026-08-25T11:20:00Z',
    updatedAt: '2026-09-04T09:10:00Z',
  },
  {
    id: 'AF-2026-0004',
    fullName: 'Meenakshi Krishnan',
    phone: '9444123987',
    email: 'meenu.krish@gmail.com',
    gender: 'Female',
    age: 38,
    address: '3B Lotus Apts, Anna Nagar East, Chennai',
    branch: 'Ayanavaram Main Branch',
    inviterType: 'Walk-in',
    counselingBy: 'Coach Rajesh Kumar',
    healthGoals: ['Weight Loss', 'Immunity Boost'],
    customerType: 'Preferred Customer',
    currentProgram: 'Preferred Lifestyle Plan',
    programDuration: '30 Days',
    durationInDays: 30,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    allottedShakes: 30,
    consumedShakes: 4,
    remainingShakes: 26,
    dailyShakeFrequency: 1,
    pricePerDay: 150,
    totalPlanCost: 4500,
    amountPaid: 3000,
    balanceDue: 1500,
    paymentStatus: 'Partial',
    paymentMethod: 'Cash',
    status: 'Active',
    clubVisitsCount: 4,
    seminarAttendanceCount: 1,
    totalOrdersCount: 2,
    totalSpent: 4790,
    createdAt: '2026-09-01T14:30:00Z',
    updatedAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'AF-2026-0005',
    fullName: 'Arun Balaji',
    phone: '9940556677',
    gender: 'Male',
    age: 26,
    address: '89 Perambur High Road, Chennai',
    branch: 'Ayanavaram Main Branch',
    inviterType: 'Coach',
    inviterName: 'Coach Ananya Roy',
    counselingBy: 'Coach Ananya Roy',
    healthGoals: ['Weight Gain', 'Muscle Hypertrophy'],
    customerType: 'New Customer',
    currentProgram: '3 Day Quick Starter Trial',
    programDuration: '3 Day Trial',
    durationInDays: 3,
    startDate: '2026-09-02',
    endDate: '2026-09-05',
    allottedShakes: 3,
    consumedShakes: 2,
    remainingShakes: 1,
    dailyShakeFrequency: 1,
    pricePerDay: 150,
    totalPlanCost: 450,
    amountPaid: 450,
    balanceDue: 0,
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    status: 'Active',
    clubVisitsCount: 2,
    seminarAttendanceCount: 0,
    totalOrdersCount: 1,
    totalSpent: 540,
    createdAt: '2026-09-02T16:00:00Z',
    updatedAt: '2026-09-03T18:00:00Z',
  }
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'ORD-1001',
    tokenNumber: 101,
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    isWalkIn: false,
    items: [
      {
        productId: 'PRD-001',
        productName: 'Mango Delight Protein Shake',
        category: 'Shakes',
        price: 0,
        quantity: 1,
        subtotal: 0,
        notes: 'Chilled with extra chia seeds (Plan Quota)',
      },
      {
        productId: 'PRD-010',
        productName: 'Lemon Fresh Energy Tea',
        category: 'Energy Teas',
        price: 90,
        quantity: 1,
        subtotal: 90,
      }
    ],
    subtotal: 90,
    tax: 0,
    discount: 0,
    total: 90,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    orderStatus: 'READY',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
    remarks: 'Regular morning shake visit',
    createdAt: '2026-09-04T10:15:00Z',
    updatedAt: '2026-09-04T10:22:00Z',
    readyAt: '2026-09-04T10:22:00Z',
  },
  {
    id: 'ORD-1002',
    tokenNumber: 102,
    customerId: 'AF-2026-0002',
    customerName: 'Priya Sundaram',
    customerPhone: '9884567890',
    isWalkIn: false,
    items: [
      {
        productId: 'PRD-007',
        productName: 'Weight Loss Blast Combo',
        category: 'Combos',
        price: 260,
        quantity: 1,
        subtotal: 260,
      }
    ],
    subtotal: 260,
    tax: 0,
    discount: 0,
    total: 260,
    paymentMethod: 'Card',
    paymentStatus: 'Paid',
    orderStatus: 'PREPARING',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
    createdAt: '2026-09-04T10:30:00Z',
    updatedAt: '2026-09-04T10:32:00Z',
  },
  {
    id: 'ORD-1003',
    tokenNumber: 103,
    customerId: 'AF-2026-0003',
    customerName: 'Vikram Venkatesh',
    customerPhone: '9790123456',
    isWalkIn: false,
    items: [
      {
        productId: 'PRD-002',
        productName: 'Chocolate Kulfi Shake (Plan Quota)',
        category: 'Shakes',
        price: 0,
        quantity: 1,
        subtotal: 0,
      },
      {
        productId: 'PRD-013',
        productName: 'Protein Booster Scoop (+10g)',
        category: 'Add-ons',
        price: 50,
        quantity: 1,
        subtotal: 50,
      }
    ],
    subtotal: 50,
    tax: 0,
    discount: 0,
    total: 50,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    orderStatus: 'PENDING',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
    createdAt: '2026-09-04T10:45:00Z',
    updatedAt: '2026-09-04T10:45:00Z',
  },
  {
    id: 'ORD-1004',
    tokenNumber: 104,
    customerId: 'WALK-IN',
    customerName: 'Walk-in Guest (Rajesh N)',
    isWalkIn: true,
    items: [
      {
        productId: 'PRD-011',
        productName: 'Peach Iced Energy Tea',
        category: 'Energy Teas',
        price: 95,
        quantity: 2,
        subtotal: 190,
      }
    ],
    subtotal: 190,
    tax: 0,
    discount: 0,
    total: 190,
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    orderStatus: 'COMPLETED',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
    createdAt: '2026-09-04T09:00:00Z',
    updatedAt: '2026-09-04T09:12:00Z',
    readyAt: '2026-09-04T09:08:00Z',
    completedAt: '2026-09-04T09:12:00Z',
  }
];

export const SEED_SHAKE_LOGS: ShakeIntakeLog[] = [
  {
    id: 'SHK-LOG-001',
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    date: '2026-09-04',
    time: '10:15',
    shakeCount: 1,
    flavorCombo: 'Mango Delight Protein Shake',
    notes: 'Energy levels feeling much higher this week',
    staffName: 'Coach Ananya Roy',
    previousBalance: 10,
    newBalance: 9,
    createdAt: '2026-09-04T10:15:00Z',
  },
  {
    id: 'SHK-LOG-002',
    customerId: 'AF-2026-0002',
    customerName: 'Priya Sundaram',
    customerPhone: '9884567890',
    date: '2026-09-04',
    time: '08:45',
    shakeCount: 1,
    flavorCombo: 'Chocolate Kulfi Shake',
    notes: 'Completed 5km morning walk before visit',
    staffName: 'Coach Rajesh Kumar',
    previousBalance: 15,
    newBalance: 14,
    createdAt: '2026-09-04T08:45:00Z',
  },
  {
    id: 'SHK-LOG-003',
    customerId: 'AF-2026-0003',
    customerName: 'Vikram Venkatesh',
    customerPhone: '9790123456',
    date: '2026-09-04',
    time: '09:10',
    shakeCount: 1,
    flavorCombo: 'Royal Rose & Cardamom Shake',
    notes: 'Good adherence to meal plan',
    staffName: 'Coach Ananya Roy',
    previousBalance: 12,
    newBalance: 11,
    createdAt: '2026-09-04T09:10:00Z',
  },
  {
    id: 'SHK-LOG-004',
    customerId: 'AF-2026-0004',
    customerName: 'Meenakshi Krishnan',
    customerPhone: '9444123987',
    date: '2026-09-04',
    time: '11:00',
    shakeCount: 1,
    flavorCombo: 'Vanilla Protein Fusion',
    notes: 'Day 4 of routine',
    staffName: 'Coach Rajesh Kumar',
    previousBalance: 27,
    newBalance: 26,
    createdAt: '2026-09-04T11:00:00Z',
  }
];

export const SEED_SEMINARS: SeminarAttendance[] = [
  {
    id: 'SEM-001',
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    date: '2026-08-20',
    topic: 'Metabolism, Fat Loss Blueprint & Daily Hydration',
    remarks: 'Asked great questions about protein timing and sleep',
    staffName: 'Coach Ananya Roy',
    attended: true,
    createdAt: '2026-08-20T17:00:00Z',
  },
  {
    id: 'SEM-002',
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    date: '2026-08-30',
    topic: 'Cellular Nutrition, Gut Health & Micro-nutrients',
    remarks: 'Understood importance of fiber and probiotic support',
    staffName: 'Coach Rajesh Kumar',
    attended: true,
    createdAt: '2026-08-30T17:30:00Z',
  },
  {
    id: 'SEM-003',
    customerId: 'AF-2026-0002',
    customerName: 'Priya Sundaram',
    customerPhone: '9884567890',
    date: '2026-08-10',
    topic: 'Healthy Active Lifestyle: Cardio vs Resistance Training',
    remarks: 'Active participant',
    staffName: 'Coach Ananya Roy',
    attended: true,
    createdAt: '2026-08-10T18:00:00Z',
  },
  {
    id: 'SEM-004',
    customerId: 'AF-2026-0003',
    customerName: 'Vikram Venkatesh',
    customerPhone: '9790123456',
    date: '2026-08-28',
    topic: 'Junior Program (JP) Habit Building & Family Wellness',
    remarks: 'Attended with family members',
    staffName: 'Coach Ananya Roy',
    attended: true,
    createdAt: '2026-08-28T16:00:00Z',
  }
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'INV-2026-0001',
    invoiceNumber: 'INV-2026-0001',
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    type: 'PROGRAM_REGISTRATION',
    items: [
      {
        description: '30 Days Weight Loss & Energy Program (30 Shakes)',
        quantity: 1,
        unitPrice: 4500,
        total: 4500,
      }
    ],
    subtotal: 4500,
    tax: 0,
    discount: 0,
    total: 4500,
    amountPaid: 4500,
    balanceDue: 0,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    date: '2026-08-15',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Coach Ananya Roy',
    notes: 'Full payment received at registration',
  },
  {
    id: 'INV-2026-0002',
    invoiceNumber: 'INV-2026-0002',
    customerId: 'AF-2026-0002',
    customerName: 'Priya Sundaram',
    customerPhone: '9884567890',
    type: 'PROGRAM_REGISTRATION',
    items: [
      {
        description: '60 Days Metabolic Reset & Wellness Plan (60 Shakes)',
        quantity: 1,
        unitPrice: 9000,
        total: 9000,
      }
    ],
    subtotal: 9000,
    tax: 0,
    discount: 0,
    total: 9000,
    amountPaid: 9000,
    balanceDue: 0,
    paymentMethod: 'Card',
    paymentStatus: 'Paid',
    date: '2026-07-20',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Coach Rajesh Kumar',
    notes: 'Payment settled via HDFC POS Terminal',
  },
  {
    id: 'INV-2026-0003',
    invoiceNumber: 'INV-2026-0003',
    orderId: 'ORD-1001',
    customerId: 'AF-2026-0001',
    customerName: 'Karthik Ramanathan',
    customerPhone: '9841234567',
    type: 'POS_ORDER',
    items: [
      {
        description: 'Mango Delight Protein Shake (Plan Quota)',
        quantity: 1,
        unitPrice: 0,
        total: 0,
      },
      {
        description: 'Lemon Fresh Energy Tea',
        quantity: 1,
        unitPrice: 90,
        total: 90,
      }
    ],
    subtotal: 90,
    tax: 0,
    discount: 0,
    total: 90,
    amountPaid: 90,
    balanceDue: 0,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    date: '2026-09-04',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
  },
  {
    id: 'INV-2026-0004',
    invoiceNumber: 'INV-2026-0004',
    orderId: 'ORD-1002',
    customerId: 'AF-2026-0002',
    customerName: 'Priya Sundaram',
    customerPhone: '9884567890',
    type: 'POS_ORDER',
    items: [
      {
        description: 'Weight Loss Blast Combo',
        quantity: 1,
        unitPrice: 260,
        total: 260,
      }
    ],
    subtotal: 260,
    tax: 0,
    discount: 0,
    total: 260,
    amountPaid: 260,
    balanceDue: 0,
    paymentMethod: 'Card',
    paymentStatus: 'Paid',
    date: '2026-09-04',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
  },
  {
    id: 'INV-2026-0005',
    invoiceNumber: 'INV-2026-0005',
    orderId: 'ORD-1003',
    customerId: 'AF-2026-0003',
    customerName: 'Vikram Venkatesh',
    customerPhone: '9790123456',
    type: 'POS_ORDER',
    items: [
      {
        description: 'Chocolate Kulfi Shake (Plan Quota)',
        quantity: 1,
        unitPrice: 0,
        total: 0,
      },
      {
        description: 'Protein Booster Scoop (+10g)',
        quantity: 1,
        unitPrice: 50,
        total: 50,
      }
    ],
    subtotal: 50,
    tax: 0,
    discount: 0,
    total: 50,
    amountPaid: 50,
    balanceDue: 0,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    date: '2026-09-04',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
  },
  {
    id: 'INV-2026-0006',
    invoiceNumber: 'INV-2026-0006',
    orderId: 'ORD-1004',
    customerId: 'WALK-IN',
    customerName: 'Walk-in Guest (Rajesh N)',
    customerPhone: 'Walk-in',
    type: 'POS_ORDER',
    items: [
      {
        description: 'Peach Iced Energy Tea',
        quantity: 2,
        unitPrice: 95,
        total: 190,
      }
    ],
    subtotal: 190,
    tax: 0,
    discount: 0,
    total: 190,
    amountPaid: 190,
    balanceDue: 0,
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    date: '2026-09-04',
    branch: 'Ayanavaram Main Branch',
    staffName: 'Pooja Sharma',
  }
];
