'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { 
  Users, Award, Sparkles, UserPlus, 
  Search, ShieldCheck, Coffee, TrendingUp, 
  ArrowUpRight, Phone, MapPin, Eye, PlusCircle, CheckCircle2 
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { formatCurrency, formatDate } from '../../lib/utils';
import { CustomerProfileModal } from '../../components/customers/CustomerProfileModal';
import { ShakeLoggerModal } from '../../components/shakes/ShakeLoggerModal';
import { SeminarLoggerModal } from '../../components/seminars/SeminarLoggerModal';
import { Badge } from '../../components/common/Badge';

export default function AssociatesPage() {
  const { customers, selectedBranch } = useApp();
  const [searchQuery, setSearchQuery] = useState('');
  const [branchFilter, setBranchFilter] = useState('All');
  const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null);
  const [shakeModalCustId, setShakeModalCustId] = useState<string | null>(null);
  const [seminarModalCustId, setSeminarModalCustId] = useState<string | null>(null);

  // Filter for Associate members (and legacy JP Member entries)
  const associates = customers.filter(c => c.customerType === 'Associate' || c.customerType === 'JP Member');

  // Filtered associates based on search and branch
  const filteredAssociates = associates.filter(c => {
    const matchesSearch = 
      c.fullName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.phone.includes(searchQuery) ||
      c.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (c.associateId && c.associateId.toLowerCase().includes(searchQuery.toLowerCase()));
    
    const matchesBranch = branchFilter === 'All' || c.branch === branchFilter;
    return matchesSearch && matchesBranch;
  });

  // Calculate total referrals generated by associates
  const getReferralCount = (associateName: string, associatePhone: string) => {
    return customers.filter(c => 
      (c.inviterName && c.inviterName.toLowerCase() === associateName.toLowerCase()) ||
      (c.inviterContact && c.inviterContact === associatePhone)
    ).length;
  };

  const totalReferralsGenerated = associates.reduce((acc, a) => acc + getReferralCount(a.fullName, a.phone), 0);
  const totalAssociateShakes = associates.reduce((acc, a) => acc + a.consumedShakes, 0);
  const totalAssociateRevenue = associates.reduce((acc, a) => acc + a.totalSpent, 0);

  const activeCustomer = customers.find(c => c.id === selectedCustomerId) || null;

  return (
    <div className="space-y-6 pb-12">
      {/* Hero Header */}
      <div className="bg-gradient-to-r from-forest-950 via-forest-900 to-[#021811] rounded-3xl p-6 sm:p-8 text-white shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 border border-brand-700/40 relative overflow-hidden">
        <div className="absolute right-0 top-0 w-80 h-80 bg-gold-400/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10">
          <div className="inline-flex items-center space-x-1.5 px-3.5 py-1 rounded-full bg-gold-500/15 border border-gold-400/40 text-gold-300 text-xs font-black tracking-wide uppercase mb-3 shadow-inner">
            <Award className="w-3.5 h-3.5 text-gold-400" />
            <span>Wellness Partner & Associate Division</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-white">
            Associate Registry & Partner Network
          </h1>
          <p className="text-xs text-brand-100/80 mt-1 max-w-2xl font-medium leading-relaxed">
            Manage Wellness Associates, track downline client referrals, monitor shake consumption, and promote active members into business partners.
          </p>
        </div>

        <Link
          href="/customers/register?type=Associate"
          className="relative z-10 px-6 py-3 rounded-2xl bg-gradient-to-r from-gold-600 to-gold-500 hover:from-gold-500 hover:to-gold-400 text-white font-black text-xs shadow-xl shadow-gold-950/20 transition-all flex items-center space-x-2 shrink-0 border border-gold-300/30 active:scale-95 cursor-pointer"
        >
          <UserPlus className="w-4 h-4" />
          <span>Enroll New Associate</span>
        </Link>
      </div>

      {/* KPI Stats HUD */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-3xl p-5 border border-emerald-100/80 shadow-sm">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Associates</p>
          <h3 className="text-2xl font-black text-slate-900 mt-1">{associates.length} Associates</h3>
          <p className="text-[11px] text-emerald-600 font-bold mt-1 flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" /> Certified Partner Network
          </p>
        </div>

        <div className="bg-white rounded-3xl p-5 border border-emerald-100/80 shadow-sm">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Client Referrals Generated</p>
          <h3 className="text-2xl font-black text-gold-900 mt-1">{totalReferralsGenerated} Members</h3>
          <p className="text-[11px] text-slate-400 font-medium mt-1">Invited & enrolled by associates</p>
        </div>

        <div className="bg-white rounded-3xl p-5 border border-emerald-100/80 shadow-sm">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Shakes Consumed</p>
          <h3 className="text-2xl font-black text-brand-700 mt-1">{totalAssociateShakes} Shakes</h3>
          <p className="text-[11px] text-slate-400 font-medium mt-1">Associate nutrition intake</p>
        </div>

        <div className="bg-white rounded-3xl p-5 border border-emerald-100/80 shadow-sm">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Lifetime Volume</p>
          <h3 className="text-2xl font-black text-emerald-700 mt-1">{formatCurrency(totalAssociateRevenue)}</h3>
          <p className="text-[11px] text-slate-400 font-medium mt-1">Plans & retail sales volume</p>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="bg-white rounded-3xl p-4 border border-emerald-100/80 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="relative flex-1 w-full sm:max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-emerald-600/70" />
          <input
            type="text"
            placeholder="Search by associate name, phone, or ID (e.g. ASC-003)..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-2xl bg-emerald-50/40 border border-emerald-200/80 text-xs text-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-500/20 focus:border-brand-500"
          />
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <span className="text-xs font-bold text-slate-500 whitespace-nowrap">Branch:</span>
          <select
            value={branchFilter}
            onChange={(e) => setBranchFilter(e.target.value)}
            className="px-3.5 py-2.5 rounded-2xl border border-emerald-200/80 bg-emerald-50/40 text-xs font-semibold text-slate-900 focus:outline-none"
          >
            <option value="All">All Branches</option>
            <option value="Ayanavaram Main Branch">Ayanavaram Main</option>
            <option value="Kilpauk Wellness Center">Kilpauk Wellness</option>
            <option value="Anna Nagar Prime Hub">Anna Nagar Prime</option>
          </select>
        </div>
      </div>

      {/* Associates Cards Grid */}
      <div className="bg-white rounded-3xl border border-emerald-100/80 shadow-sm p-6 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
            <Award className="w-4 h-4 text-gold-600" />
            <span>Registered Associate Roster</span>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-gold-100 text-gold-900 font-bold border border-gold-300">
              {filteredAssociates.length} Associates
            </span>
          </h3>
        </div>

        {filteredAssociates.length === 0 ? (
          <div className="text-center py-12 bg-emerald-50/20 rounded-3xl border border-dashed border-emerald-200">
            <Users className="w-10 h-10 text-slate-300 mx-auto mb-2" />
            <p className="text-xs font-bold text-slate-600">No associates found matching your search.</p>
            <p className="text-[11px] text-slate-400 mt-1">Enroll a new associate or shift an existing member to Associate from Customer 360.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredAssociates.map(cust => {
              const referralCount = getReferralCount(cust.fullName, cust.phone);
              const associateId = cust.associateId || `ASC-${cust.id.replace('AF-', '')}`;
              const progressPct = cust.allottedShakes > 0 ? (cust.consumedShakes / cust.allottedShakes) * 100 : 0;

              return (
                <div
                  key={cust.id}
                  className="bg-emerald-50/30 hover:bg-emerald-50/60 rounded-3xl p-5 border border-emerald-100/80 hover:border-brand-300 transition-all space-y-4 shadow-xs"
                >
                  {/* Top Header */}
                  <div className="flex items-start justify-between">
                    <div className="flex items-center space-x-3">
                      <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-gold-500 to-amber-300 text-forest-950 font-black text-sm flex items-center justify-center shadow-md border border-gold-300">
                        {cust.fullName.split(' ').map(n => n[0]).slice(0, 2).join('')}
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-black text-slate-900 text-sm">{cust.fullName}</h4>
                          <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-md bg-gold-100 text-gold-900 border border-gold-300">
                            {associateId}
                          </span>
                        </div>
                        <p className="text-xs text-slate-500 font-medium mt-0.5">
                          {cust.phone} • {cust.branch.split(' ')[0]}
                        </p>
                      </div>
                    </div>

                    <Badge variant="gold">
                      Associate
                    </Badge>
                  </div>

                  {/* Metrics Row */}
                  <div className="grid grid-cols-3 gap-2 bg-white/80 rounded-2xl p-3 border border-emerald-100/60 text-center">
                    <div>
                      <p className="text-[10px] text-slate-400 font-bold uppercase">Referrals</p>
                      <p className="text-sm font-black text-gold-800">{referralCount} Clients</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 font-bold uppercase">Shakes Left</p>
                      <p className="text-sm font-black text-brand-700">{cust.remainingShakes}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 font-bold uppercase">Total Volume</p>
                      <p className="text-sm font-black text-slate-900">{formatCurrency(cust.totalSpent)}</p>
                    </div>
                  </div>

                  {/* Shake Progress Bar */}
                  <div>
                    <div className="flex justify-between text-[11px] mb-1 font-medium text-slate-600">
                      <span>Shake Quota: {cust.consumedShakes}/{cust.allottedShakes} used</span>
                      <span className="font-bold text-brand-800">{Math.round(progressPct)}%</span>
                    </div>
                    <div className="w-full bg-emerald-100/80 rounded-full h-2 overflow-hidden">
                      <div
                        className="bg-gradient-to-r from-brand-600 to-gold-400 h-full rounded-full transition-all duration-300"
                        style={{ width: `${Math.min(100, progressPct)}%` }}
                      />
                    </div>
                  </div>

                  {/* Remarks preview if present */}
                  {cust.remarks && (
                    <p className="text-[11px] text-slate-600 bg-white/60 px-3 py-1.5 rounded-xl border border-emerald-100/70 truncate">
                      <span className="font-bold text-slate-700">Note:</span> {cust.remarks}
                    </p>
                  )}

                  {/* Actions */}
                  <div className="pt-2 border-t border-emerald-100 flex items-center justify-between">
                    <button
                      type="button"
                      onClick={() => setShakeModalCustId(cust.id)}
                      className="px-3.5 py-1.5 rounded-xl bg-brand-50 text-brand-900 hover:bg-brand-100 text-xs font-bold flex items-center gap-1 transition-colors border border-brand-200"
                    >
                      <Coffee className="w-3.5 h-3.5" />
                      <span>Log Shake</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => setSelectedCustomerId(cust.id)}
                      className="px-4 py-1.5 rounded-xl bg-white hover:bg-slate-50 text-slate-800 text-xs font-bold flex items-center gap-1.5 border border-slate-200 shadow-xs transition-colors"
                    >
                      <Eye className="w-3.5 h-3.5 text-brand-600" />
                      <span>Associate 360</span>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Customer 360 Drawer Modal */}
      <CustomerProfileModal
        isOpen={!!selectedCustomerId}
        onClose={() => setSelectedCustomerId(null)}
        customer={activeCustomer}
        onOpenShakeLogger={(id) => {
          setSelectedCustomerId(null);
          setShakeModalCustId(id);
        }}
        onOpenSeminarLogger={(id) => {
          setSelectedCustomerId(null);
          setSeminarModalCustId(id);
        }}
      />

      {/* Shake Intake Modal */}
      <ShakeLoggerModal
        isOpen={!!shakeModalCustId}
        onClose={() => setShakeModalCustId(null)}
        preSelectedCustomerId={shakeModalCustId || undefined}
      />

      {/* Seminar Logger Modal */}
      <SeminarLoggerModal
        isOpen={!!seminarModalCustId}
        onClose={() => setSeminarModalCustId(null)}
        preSelectedCustomerId={seminarModalCustId || undefined}
      />
    </div>
  );
}
